FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt into the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install -r requirements.txt


# Copy the rest of your app files
COPY . .

# Run your application
CMD ["python", "mqtt_to_mongo.py"]
