services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - my_network
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_WEB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_WEB_PASSWORD}
    networks:
      - my_network

  mqtt-to-mongo:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - ./app:/usr/src/app
      
    networks:
      - my_network


    
volumes:
  mongo-data:
networks:
  my_network:
   external: true 

